disk_cache:
  enabled: true
download:
  icons: true
  multithreaded: true
gems:
- web
- arch
- appimage
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: true
  hdpi: true
  style: gtk2
  table:
    max_displayed: 50
  tray:
    default_icon: null
    updates_icon: null
updates:
  check_interval: 30
